#!/bin/bash
mkdir -p bin
go build -a --ldflags '-extldflags "-static"' -tags netgo -installsuffix netgo -o bin/server ./server
go build -a --ldflags '-extldflags "-static"' -tags netgo -installsuffix netgo -o bin/client ./client
