#!/bin/bash
mkdir -p bin
go build -a --ldflags '-extldflags "-static"' -tags netgo -installsuffix netgo -o bin/streaming-server ./streaming-server
go build -a --ldflags '-extldflags "-static"' -tags netgo -installsuffix netgo -o bin/streaming-client ./streaming-client
go build -a --ldflags '-extldflags "-static"' -tags netgo -installsuffix netgo -o bin/secure-server ./secure-server
go build -a --ldflags '-extldflags "-static"' -tags netgo -installsuffix netgo -o bin/secure-client ./secure-client
