# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2
jobs:
  build:
    docker:
      # specify the version
      - image: circleci/golang:1.8

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4

    working_directory: /go/src/github.com/jnbnyc/helloworld
    steps:
      - checkout
      - run: go get github.com/jstemmer/go-junit-report

      - run: go get -v -t -d ./...
      - run: go test -v ./... -bench . -benchmem -cover 2>&1 | tee report.out
      - run: go-junit-report -set-exit-code < report.out > report.xml
      - store_test_results:
          path: report.xml
      - setup_remote_docker:
          docker_layer_caching: true
      - run: docker build .
      - run: docker images
