name: Push Docker Image

on:
  create:

jobs:
  new-branch:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Hello, World in GitHub Actions
        run: echo "Hello, World"
